SHOW DATABASES;

USE college;

#create a table
CREATE TABLE STUDENT (
student_id INT PRIMARY KEY,
name VARCHAR(50),
age INT,
city VARCHAR(50)
)

SELECT * FROM STUDENT;

#insert some values
INSERT INTO STUDENT VALUES
(1,"SANJAY N",21,"VELLORE"),
(2,"Ragul N",18,"VELLORE"),
(3,"Sandeep",21,"VELLORE");

SELECT * FROM STUDENT;

#alter table
ALTER TABLE STUDENT
ADD email VARCHAR(50);
SELECT * FROM STUDENT;

ALTER TABLE STUDENT
MODIFY city VARCHAR(100);
SELECT * FROM STUDENT;

ALTER TABLE STUDENT
DROP COLUMN email;
SELECT * FROM STUDENT;

#truncate table
TRUNCATE TABLE STUDENT;
SELECT * FROM STUDENT;

#drop table
DROP TABLE STUDENT;